config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'tickets#index', as: :authenticated_root
    end
    unauthenticated do
      root 'pages#home', as: :unauthenticated_root
    end
  end
  resources :vehicles, only: [:index, :show, :update]
  resources :tickets, except: [:delete]
  resources :parking_zones, only: [:index, :show]
  get '/report_data', to: 'tickets#report_data', as: 'report_data'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'arqueo', to: 'tickets#arqueo', as: 'arqueo'
  get 'landing', to: 'parking_zones#landing', as: 'landing'
  get '/solicitar-demo', to: 'pages#demo', as: 'demo'

  # Sidekiq Web UI, only for admins.
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_cards.html.erb
  <div class="col-xs-12 no-padding" >
    <div class="card">
      <% unless ticket.exit? %>
        <%= link_to ticket_path(ticket), class: "card-link card-linkeable" do %>
          <div class="card-car-icon">
            <i class="material-icons car-size-big">
              directions_car
            </i>
          </div>
          <div class="card-car-central">
            <div class="card-car-central-main">
              <%= ticket.vehicle.plate.upcase %>
            </div>
            <div class="card-car-central-sec">
              <%= parking_time(ticket.entry) %>
              <%#= "Registrado hace " + distance_of_time_in_words_to_now(ticket.entry, include_seconds: true) %>
            </div>
          </div>
        <% end %>
        <div class="card-car-right">
          <div class="mdc-menu material-menu-container">
            <ul class="mdc-menu__items mdc-list" role="menu" aria-hidden="true">
              <li class="mdc-list-item" role="menuitem" tabindex="0">
                <%= simple_form_for(ticket.vehicle) do |f| %>
                  <%= f.association :tickets, as: :hidden, input_html: { value: ticket.id }%>
                  <button class="menu-charge-btn" type="submit" style="cursor:pointer;" data-confirm="Estás seguro que deseas reportar el vehiculo <%= ticket.vehicle.plate %>">
                    <i class="material-icons">
                      error_outline
                    </i>
                    <div class="bottom-menu-option-text">
                      Reportar
                    </div>
                  </button>
                <% end %>
              </li>
              <li class="mdc-list-item" role="menuitem" tabindex="0">
                <% string = "com.fidelier.printfromweb://$intro$$intro$$biguhw$TIQUETE DE PARQUEADERO$intro$$intro$->Id del Tiquete: #{ticket.id}$intro$->Hora ingreso: #{ticket.entry.strftime("%x")}-#{ticket.entry.strftime("%R")}$intro$->Placa Del Vehiculo: #{ticket.vehicle.plate}$intro$->Zona: #{ticket.parking_zone.name}$intro$->Pago Anticipado: #{ticket.charge_paid_cents}$intro$$intro$$intro$$intro$$cut$$intro$" %>
                <a href="<%= string %>" class="menu-charge-btn link-to-btn-style" style="cursor:pointer;">
                  <i class="material-icons">
                    print
                  </i>
                  <div class="bottom-menu-option-text">
                    Imprimir
                  </div>
                </a>
              </li>
              <li class="mdc-list-item" role="menuitem" tabindex="0">
                <%= link_to vehicle_path(ticket.vehicle),  class: "menu-charge-btn link-to-btn-style" do %>
                  <i class="material-icons">
                    description
                  </i>
                  <div class="bottom-menu-option-text">
                    Historial
                  </div>
                <% end %>
              </li>
            </ul>
          </div>
          <i class="fas fa-ellipsis-v menu-button" ></i>
        </div>
      <% else %>
        <%= link_to ticket_path(ticket), class: "card-link card-linkeable" do %>
          <div class="card-car-icon">
            <i class="material-icons car-size-big">
              directions_car
            </i>
          </div>
          <div class="card-car-central">
            <div class="card-car-central-main">
              <%= ticket.vehicle.plate.upcase %>
            </div>
            <div class="card-car-central-sec">
              <% if ticket.status == "pagado" %>
                <%= paid_time(ticket.entry, ticket.exit) %>
              <% else %>
                <% count = (ticket.update_charge + ticket.charge_paid_cents.to_money)/ticket.parking_zone.price %>
                <%= pluralize(count.to_i, "Hora reportada", "Horas reportadas") %>
                <%#= penalty_time(ticket.entry, ticket.exit) %>
              <% end %>
            </div>
          </div>
        <% end %>
          <div class="card-car-right">
            <i class="fas fa-dollar-sign fa-sm"></i>
            <%= humanized_money(ticket.charge) %>
          </div>
      <% end %>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <script>
    swal({
          title: "",
          text: "<%= notice %>",
          icon: "success"
        });
  </script>
<% end %>

<% if alert %>
  <script>
    swal({
          title: "",
          text: "<%= alert %>",
          icon: "error"
        });
  </script>
<% end %>

app/views/shared/_google_analytics_tags.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-128425334-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-128425334-1');
</script>

app/views/shared/_navbar.html.erb
<% unless (controller_name == "parking_zones" && action_name == "landing") %>
  <div class="navbar-wagon">
    <div class="navbar-wagon-item">

        <% if params[:plate].present? || action_name == "show" || action_name == "new" || action_name == "arqueo" || controller_name == "parking_zones" %>
          <%= link_to :back do %>
            <i class="material-icons navbar-wagon-icon">
              arrow_back
            </i>
          <% end %>
        <% else %>
          <i class="material-icons navbar-wagon-dropicon">
            menu
          </i>
        <% end %>
        <div id="mySidenav" class="sidenav">
          <div class="sidenav-header">
            <h4>Apparki</h4>
          </div>
          <% if user_signed_in? %>
            <a class="closebtn">&times;</a>
            <%= link_to tickets_path do %>
              <i class="fas fa-home"></i> Inicio
            <% end %>
            <%= link_to new_ticket_path do %>
              <i class="fas fa-plus-circle"></i> Crear ticket
            <% end %>
            <%= link_to arqueo_path do %>
              <i class="fas fa-hand-holding-usd"></i> Cuentas
            <% end %>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          <% else %>
            <a class="closebtn">&times;</a>
            <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <% end %>
        </div>
    </div>
    <div class="navbar-wagon-item">
      <%= link_to current_user.blank? ? unauthenticated_root_path : authenticated_root_path, class: "navbar-wagon-brand" do %>
        <h4>Apparki</h4>
      <% end %>
    </div>
    <% unless controller_name == "tickets" && action_name == "index" %>
      <div class="navbar-wagon-item item-hidden">
    <% else %>
      <div class="navbar-wagon-item">
    <% end %>
        <i class="material-icons navbar-wagon-icon <%= "item-hidden" if @filtered %>" data-toggle="modal" data-target="#myModal">
          search
        </i>
        <% hide = @filtered ? "" : "hidden" %>
        <%= link_to tickets_path, class: "navbar-wagon-item #{hide}" do%>
          <i class="material-icons navbar-wagon-icon">
            close
          </i>
        <% end %>
      </div>
  </div>
  <%= render 'shared/search-plate-modal' %>
<% end %>

app/views/shared/_parking_zone_cards.html.erb
<div class="col-xs-12 no-padding" >
  <div class="card">
    <%= link_to parking_zone_path(pk), class: "card-link card-linkeable" do %>
      <div class="card-car-icon">
        <i class="material-icons car-size-big">
          local_parking
        </i>
      </div>
      <div class="card-car-central flex-item-65 bottom-space-small">
        <div class="card-car-central-main">
          <%= pk.name %>
        </div>
        <div class="card-car-central-sec color-gray">
          A 500 metros del parque
        </div>
        <div class="card-car-central-sec color-gray">
          Disponibilidad: alta
        </div>
      </div>
      <div class="card-car-right">
        <i class="fas fa-dollar-sign fa-sm"></i>
        <%= humanize_price(pk.price) %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_search-plate-modal.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= form_with url: tickets_path, class: "search-plate-form", method: :get, local: true do |f|%>
        <h4 class="modal-title" id="myModalLabel">Buscar por placa</h4>
        <div class="mdc-text-field ticket-plate">
          <input
            type="text"
            id="navbar-text-field"
            name="plate"
            class="mdc-text-field__input"
            maxlength="6"
            value = <%= params[:plate] unless params[:plate].blank? %>>
          <label class="mdc-floating-label" for="navbar-text-field">Placa del vehículo</label>
          <div class="mdc-line-ripple"></div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="col-xs-6">
          <button type="button" class="mdc-button button-margin" data-dismiss="modal">Cancelar</button>
        </div>
        <div class="col-xs-6">
          <%= f.submit "Buscar", class: "mdc-button mdc-button--raised button-margin" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_ticket_form.html.erb
<%= simple_form_for(@ticket, remote: true) do |f| %>
  <div class="col-xs-3">
    <div class="image-preview-container">
      <div class="image-preview" style="cursor: pointer; background-image: url('#');" id="img_prev">
        <label class="file optional" for="ticket_picture">
          <i class="material-icons">
            photo_camera
          </i>
        </label>
        <%= f.input :picture, label: false%>
      </div>
      <%= f.input :picture_cache, as: :hidden %>
    </div>
  </div>
  <div class="col-xs-9">
    <h1 class="mdc-typography--headline1">Nuevo Tiquete de Parqueadero</h1>
  </div>
  <div class="col-xs-12">
    <%= f.error_notification %>
  </div>
  <% if  Time.zone.now  <= Time.zone.now.change(hour: 7) %>
    <%= f.input :entry, as: :hidden, input_html: { value: Time.zone.now.change(hour: 7) }%>
  <% else %>
    <%= f.input :entry, as: :hidden, input_html: { value: Time.zone.now }%>
  <% end %>
    <div class="col-xs-12 col-margin">
      <div class="mdc-text-field ticket-plate <%= "invalid-vehicle-plate" unless @ticket.errors.messages[:vehicle].empty? %>">
        <input
          type="text"
          id="my-text-field"
          name="vehicle[plate]"
          class="mdc-text-field__input"
        maxlength="6"
        value = <%= @ticket.vehicle.plate unless @ticket.vehicle.blank? %>>
      <label class="mdc-floating-label" for="my-text-field">Placa del vehículo</label>
      <div class="mdc-line-ripple"></div>
    </div>
    <% @ticket.errors.messages[:vehicle].each do |message|%>
      <div class="validation-error">La placa: <%= message %></div>
    <% end %>
  </div>
  <div class="col-xs-12 col-margin">
    <div class="mdc-select ticket-select <%= "invalid-vehicle-plate" unless @ticket.errors.messages[:parking_zone].empty? %>">
      <select class="mdc-select__native-control" name="ticket[parking_zone_id]" id="ticket_parking_zone_id">
        <option value="" disabled <%= "selected" if @ticket.parking_zone_id.blank?%>></option>
        <% @parking_zones.each do |zone| %>
          <% picked_condition =  @ticket.parking_zone_id==zone.id || current_user==zone.user%>
          <option value=<%= zone.id %> <%= "selected" if picked_condition%>> <%= zone.name %></option>
        <% end %>
      </select>
      <label class="mdc-floating-label">Seleccione la zona</label>
      <div class="mdc-line-ripple"></div>
    </div>
    <% @ticket.errors.messages[:parking_zone].each do |message|%>
      <div class="validation-error">Zona de parqueo: <%= message %></div>
    <% end %>
  </div>
  <div class="col-xs-12 col-margin">
    <div class="mdc-form-field padding-top-10">
      <div class="mdc-checkbox checkbox-color">
        <input type="checkbox"
               class="mdc-checkbox__native-control"
               name="ticket[charge_paid_cents]"
               id="checkbox_anticipo"/>
        <div class="mdc-checkbox__background">
          <svg class="mdc-checkbox__checkmark"
               viewBox="0 0 24 24">
            <path class="mdc-checkbox__checkmark-path"
                  fill="none"
                  d="M1.73,12.91 8.1,19.28 22.79,4.59"/>
          </svg>
          <div class="mdc-checkbox__mixedmark checkbox-color"></div>
        </div>
      </div>
      <label for="checkbox_anticipo" class="normal-text-weight">Anticipo pagado</label>
    </div>
  </div>
  <%= f.input :status, as: :hidden, input_html: { value: "pendiente" }%>
  <div class="col-xs-6 col-margin">
    <%= link_to "CANCELAR", tickets_path,  class: "mdc-button button-margin" %>
  </div>
  <div class="col-xs-6 col-margin">
    <%= f.submit "Imprimir",  class: "mdc-button mdc-button--raised button-margin" %>
    <a href="#" id="linkImpresora"></a>
  </div>
<% end %>

app/views/shared/_vehicle_show_cards.html.erb
<div class="col-xs-12 no-padding" >
  <div class="card">
    <% unless ticket.exit? %>
      <%= link_to ticket_path(ticket), class: "card-link card-linkeable" do %>
        <div class="card-car-icon">
          <i class="material-icons car-size-big">
            directions_car
          </i>
        </div>
        <div class="card-car-central">
          <div class="card-car-central-main">
            <%= ticket.vehicle.plate.upcase %>
          </div>
          <div class="card-car-central-sec">
            <%= "Registrado hace " + distance_of_time_in_words_to_now(ticket.entry, include_seconds: true) %>
          </div>
        </div>
      <% end %>
      <div class="card-car-right">
        <div class="mdc-menu material-menu-container">
          <ul class="mdc-menu__items mdc-list" role="menu" aria-hidden="true">
            <li class="mdc-list-item" role="menuitem" tabindex="0">
              <%= simple_form_for(ticket.vehicle) do |f| %>
                <%= f.association :tickets, as: :hidden, input_html: { value: ticket.id }%>
                <button class="menu-charge-btn" type="submit" style="cursor:pointer;" data-confirm="Estás seguro que deseas reportar el vehiculo <%= ticket.vehicle.plate %>">
                  <i class="material-icons">
                    error_outline
                  </i>
                  <div class="bottom-menu-option-text">
                    Reportar
                  </div>
                </button>
              <% end %>
            </li>
            <li class="mdc-list-item" role="menuitem" tabindex="0">
              <% string = "com.fidelier.printfromweb://$intro$$intro$$biguhw$TIQUETE DE PARQUEADERO$intro$$intro$->Id del Tiquete: #{ticket.id}$intro$->Hora ingreso: #{ticket.entry.strftime("%x")}-#{ticket.entry.strftime("%R")}$intro$->Placa Del Vehiculo: #{ticket.vehicle.plate}$intro$->Zona: #{ticket.parking_zone.name}$intro$->Pago Anticipado: #{ticket.charge_paid_cents}$intro$$intro$$intro$$intro$$cut$$intro$" %>
              <a href="<%= string %>" class="menu-charge-btn link-to-btn-style" style="cursor:pointer;">
                <i class="material-icons">
                  print
                </i>
                <div class="bottom-menu-option-text">
                  Imprimir
                </div>
              </a>
            </li>
          </ul>
        </div>
        <i class="fas fa-ellipsis-v menu-button" ></i>
      </div>
    <% else %>
      <%= link_to ticket_path(ticket), class: "card-link card-linkeable" do %>
        <div class="card-car-icon">
          <i class="material-icons car-size-big">
            directions_car
          </i>
        </div>
        <div class="card-car-central">
          <div class="card-car-central-main">
            <%= ticket.vehicle.plate.upcase %>
          </div>
          <div class="card-car-central-sec">
            <% if ticket.status == "pagado" %>
              <%= "Pagado hace " + distance_of_time_in_words_to_now(ticket.exit, include_seconds: true) %>
            <% else %>
              <%= "Reportado hace " + distance_of_time_in_words_to_now(ticket.exit, include_seconds: true) %>
            <% end %>
          </div>
        </div>
      <% end %>
        <div class="card-car-right">
          <i class="fas fa-dollar-sign fa-sm"></i>
          <%= humanized_money(ticket.charge) %>
        </div>
    <% end %>
  </div>
</div>