config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'tickets#index', as: :authenticated_root
    end
    unauthenticated do
      root 'pages#home', as: :unauthenticated_root
    end
  end
  resources :vehicles, only: [:index, :show, :update]
  resources :tickets, except: [:delete]
  resources :parking_zones, only: [:index, :show]
  get '/report_data', to: 'tickets#report_data', as: 'report_data'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'arqueo', to: 'tickets#arqueo', as: 'arqueo'
  get 'landing', to: 'parking_zones#landing', as: 'landing'
  get '/solicitar-demo', to: 'pages#demo', as: 'demo'

  # Sidekiq Web UI, only for admins.
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/pages/dashboard.html.erb
<% ActiveRecord::Base.default_timezone = :utc %>
<div class="card-container bottom-space">
  <div class="align-right">
    <div class="mdc-button export-btn-margin text-white background-gray">
      <i class="material-icons mdc-button__icon" aria-hidden="true">cloud_download</i>
      <%= link_to "Exportar a excel", dashboard_path(format: "xlsx"), class: "text-white" %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="graph-container">
        <h5 class="graph-title"> Ingresos diarios - semana actual </h5>
        <%= column_chart @week_tickets.group_by_day(:entry, format: "%a", time_zone: "Bogota").sum(:charge_cents), xtitle: "Día", ytitle: "Ingresos", label: "Recaudo"%>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="graph-container">
        <h5 class="graph-title"> Ingresos semanales - mes actual </h5>
        <%= column_chart @month_tickets.group_by_week(:entry, format: "%v", time_zone: "America/Bogota").sum(:charge_cents), xtitle: "Semana", ytitle: "Ingresos"%>
      </div>
    </div>
    <div class="col-xs-12 col-md-12">
      <div class="graph-container">
        <h5 class="graph-title"> Ingresos diarios por zona de parqueo - mes actual </h5>
          <%= line_chart ParkingZone.all.map { |pz|
              {name: pz.name, data: @month_tickets.where(parking_zone: pz).group_by_day(:entry, format: "%v", time_zone: "America/Bogota").sum(:charge_cents) }
          }, xtitle: "Semana", ytitle: "Ingresos"%>
      </div>
    </div>
    <div class="col-xs-12 col-md-8">
      <div class="graph-container">
        <h5 class="graph-title"> Ingresos semanales por zona de parqueo - mes actual </h5>
          <%= column_chart ParkingZone.all.map { |pz|
              {name: pz.name, data: @month_tickets.where(parking_zone: pz).group_by_week(:entry, format: "%v", time_zone: "America/Bogota").sum(:charge_cents)}
          }, xtitle: "Semana", ytitle: "Ingresos"%>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <div class="graph-container">
        <h5 class="graph-title"> Porcentaje de ingresos por zonas de parqueo </h5>
        <%= pie_chart Ticket.joins(:parking_zone).group(:name).sum(:charge_cents)%>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="graph-container">
        <h5 class="graph-title"> Ingresos diarios por usuario - semana actual </h5>
        <%= column_chart User.group(:email).joins(:entry_tickets).group_by_day(:entry, time_zone: "America/Bogota", format: "%a").where(tickets: {entry: @beginning_of_week..@end_of_week}).sum(:charge_cents), xtitle: "Día", ytitle: "Ingresos"%>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="graph-container">
        <h5 class="graph-title"> Ingresos mensuales - año actual </h5>
        <%= column_chart Ticket.all.group_by_month(:entry, format: "%B", time_zone: "America/Bogota").sum(:charge_cents), xtitle: "Mes", ytitle: "Ingresos", label: "Recaudo"%>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <h5 class="graph-title table-title"> Vehículos con pago pendiente </h5>
      <div class="table-container">
        <table class="paleBlueRows">
          <thead>
            <tr>
              <th>Placa</th>
              <th>Fecha de ingreso</th>
              <th>Fecha de reporte</th>
              <th>Deuda pendiente</th>
            </tr>
          </thead>
          <% @reported_tickets.order('charge_cents DESC').each do |ticket| %>
            <tr>
              <td><%= ticket.vehicle.plate %></td>
              <td><%=ticket.entry.strftime('%x - %H:%M:%S') %></td>
              <td><%=ticket.exit.strftime('%x - %H:%M:%S') %></td>
              <td>$ <%= humanize_price(ticket.charge) %></td>
            </tr>
          <% end %>
          <tfoot>
            <tr>
              <td>Total</td>
              <td></td>
              <td></td>
              <td>$ <%= humanize_price(@reported_tickets.sum(:charge_cents)/100) %></td>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>
<% ActiveRecord::Base.default_timezone = :local %>

app/views/pages/demo.html.erb
<div class="demo-banner">
  <div class="demo-banner-content">
    <h1>¡Agenda un demo sin costo!</h1>
    <p>Completa el formulario y prueba APPARKI durante 30 días.</p>
  </div>
</div>

<!-- Begin MailChimp Signup Form -->
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3 demo-form-wrapper">
      <div id="mc_embed_signup">
        <form action="https://scuad.us18.list-manage.com/subscribe/post?u=ee49f2fa85f6823ca64e930e9&amp;id=db8f16fdc2" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate form-inline" target="_blank" novalidate>
            <div id="mc_embed_signup_scroll">
        <div class="mc-field-group form-group">
          <label for="mce-FNAME">Nombre Contacto</label>
          <input type="text" value="" name="FNAME" class="form-control" id="mce-FNAME">
        </div>
        <div class="mc-field-group form-group">
          <label for="mce-EMAIL">Correo Electrónico de Contacto
        </label>
          <input type="email" value="" name="EMAIL" class="required email form-control" id="mce-EMAIL">
        </div>
        <div class="mc-field-group form-group size1of2">
          <label for="mce-PHONE">Celular de Contacto </label>
          <input type="text" name="PHONE" class="form-control" value="" id="mce-PHONE">
        </div>
        <div class="mc-field-group form-group">
          <label for="mce-MMERGE2">Nombre de la Empresa </label>
          <input type="text" value="" name="MMERGE2" class="form-control" id="mce-MMERGE2">
        </div>
          <div id="mce-responses" class="clear">
            <div class="response" id="mce-error-response" style="display:none"></div>
            <div class="response" id="mce-success-response" style="display:none"></div>
          </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
            <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_ee49f2fa85f6823ca64e930e9_db8f16fdc2" tabindex="-1" value=""></div>
            <div class="clear"><input type="submit" value="SOLICITAR DEMO" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[1]='FNAME';ftypes[1]='text';fnames[0]='EMAIL';ftypes[0]='email';fnames[4]='PHONE';ftypes[4]='phone';fnames[2]='MMERGE2';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
<!--End mc_embed_signup-->

app/views/pages/home.html.erb
<div class="navbar-wagon navbar-wagon-transparent">
  <!-- Logo -->
  <h3>Apparki</h3>
  <div class="navbar-wagon-right hidden-xs">
    <%= link_to "Ingresar", new_user_session_path, class: "btn mdc-button mdc-button button-margin navbar-wagon-item navbar-wagon-link"  %>
    <%= link_to "Solicitar Demo", demo_path, class: "btn mdc-button mdc-button--outlined button-margin navbar-wagon-item navbar-wagon-link"  %>
  </div>
</div>
<div class="banner">
  <div class="banner-content">
    <h1>Administra tu parqueadero en la nube y desde tu celular</h1>
    <p>Registra, cobra y analiza tu negocio en un mismo lugar</p>
    <%= link_to "Ingresar",new_user_session_path, class:"btn mdc-button button-margin hidden-sm hidden-md hidden-lg" %>
    <%= link_to "Solicitar Demo", demo_path, class:"btn mdc-button mdc-button--raised button-margin" %>
  </div>
  <%= render 'shared/sumni' %>
</div>
<div class="home-page-section">
  <div class="section-content-div mdc-elevation--z3">
    <h2>Gestionar tu parqueadero nunca fue tan sencillo</h2>
    <div class="section-list-container">
      <div class="row">
        <div class="col-xs-12 col-sm-4">
          <div class="section-content-div-element">
            <div class="list-element-icon">
              <i class="fas fa-money-bill"></i>
            </div>
            <h4>Simplifica las transacciones</h4>
            <p>
              Registra los vehiculos de forma rápida y sencilla, revisa el estado de caja en cualquier momento y no te preocupes más por calcular la tarifa, la app lo hará por ti.
            </p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="section-content-div-element">
            <div class="list-element-icon">
              <i class="fas fa-parking"></i>
            </div>
            <h4>Disponibilidad de parqueaderos</h4>
            <p>
              Los usuarios de tu parqueadero podrán ver las celdas disponibles, incluso antes de salir de su lugar de partida.
            </p>
          </div>
        </div>
        <div class="col-xs-12 col-sm-4">
          <div class="section-content-div-element">
            <div class="list-element-icon">
              <i class="fas fa-chart-bar"></i>
            </div>
            <h4>Reportes en tiempo real</h4>
            <p>
              Accede en cualquier momento a la información transaccional de tu negocio, compara ingresos semanales y mensuales, encuentra la tasa de ocupación de tu parqueadero y más.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>