config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'tickets#index', as: :authenticated_root
    end
    unauthenticated do
      root 'pages#home', as: :unauthenticated_root
    end
  end
  resources :vehicles, only: [:index, :show, :update]
  resources :tickets, except: [:delete]
  resources :parking_zones, only: [:index, :show]
  get '/report_data', to: 'tickets#report_data', as: 'report_data'
  get 'dashboard', to: 'pages#dashboard', as: 'dashboard'
  get 'arqueo', to: 'tickets#arqueo', as: 'arqueo'
  get 'landing', to: 'parking_zones#landing', as: 'landing'
  get '/solicitar-demo', to: 'pages#demo', as: 'demo'

  # Sidekiq Web UI, only for admins.
  require 'sidekiq/web'
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/parking_zone.rb
class ParkingZone < ApplicationRecord
  belongs_to :user
  has_many :tickets

  monetize :price_cents

  validates :name, :city, :price, presence: true
  validates :name, uniqueness: { scope: :city }
end

app/controllers/parking_zones_controller.rb
class ParkingZonesController < ApplicationController
  skip_after_action :verify_authorized, only: :landing
  before_action :set_parking_zone, only: [:show]

  def landing
  end

  def index
    @parking_zones = policy_scope(ParkingZone.all)
    @parking_zones = @parking_zones.where(vehicle_type: params[:vehicle_type])
  end

  def show
    authorize @parking_zone
  end

  private

  def parking_zone_params
    params.require(:parking_zone).permit(:vehicle_type)
  end

  def set_parking_zone
    @parking_zone = ParkingZone.find(params[:id])
  end
end

app/views/parking_zones/index.html.erb
<div class="card-container">
  <div class="row">
    <% @parking_zones.each do |pk| %>
      <%= render 'shared/parking_zone_cards', pk: pk %>
    <% end %>
  </div>
</div>

app/views/parking_zones/landing.html.erb
<div class="parking-zone-banner">
  <div class="parking-zone-banner-content">
    <h1>Apparki</h1>
    <h3 class="margin-center">Encuentra un lugar para estacionar</h3>
    <h4>Buscas estacionamiento para:</h4>
    <div class="option-buttons flex flex-align-center flex-space-around">
      <%= link_to "Carro", parking_zones_path(vehicle_type: "car" ), class: "mdc-button mdc-button--raised button-margin btn-width-medium btn-side-margin" %>
      <%= link_to "Moto", parking_zones_path(vehicle_type: "bike" ), class: "mdc-button mdc-button--raised button-margin btn-width-medium btn-side-margin" %>
    </div>
  </div>
</div>

app/views/parking_zones/show.html.erb
<h1>ParkingZones#show</h1>
<p>Find me in app/views/parking_zones/show.html.erb</p>